version: 0.0
os: linux
files:
  - source: /
    destination: /opt/var/backend
#   - source: server_configs/nginx/backend.conf
#     destination: /etc/nginx/sites-enabled/
#     runas: ubuntu
#   - source: server_configs/nginx/backend.conf
#     destination: /etc/nginx/sites-available/
#     runas: ubuntu
#   - source: server_configs/supervisor/backend_supervisor.conf
#     destination: /etc/supervisor/conf.d
#     runas: ubuntu
hooks:
  AfterInstall:
      - location: backend/after_install.sh