version: 0.2

# env:
#   variables:
#     DB_ROOT_PASSWORD: "password"
#     DB_HOST: "localhost"
#     DB_PASSWORD: "password"
#     DB_SOCKET: "/var/run/mysqld/mysqld.sock"
#     KEYID: "5072E1F5"

phases:
  # pre_build:
  #   commands:
  #     - echo "Before running build"
  #     - /env/bin/python3 -m pip install --upgrade pip
  #     - sudo ls /root
  #     - pip install -r requirements.txt
  #     - echo "mysql-server mysql-server/root_password password ${DB_ROOT_PASSWORD}" |debconf-set-selections
  #     - echo "mysql-server mysql-server/root_password_again password ${DB_ROOT_PASSWORD}" |debconf-set-selections
  #     - apt-key adv --keyserver hkp://keys.gnupg.net --recv-keys ${KEYID} || apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ${KEYID}
  #     - chmod a+x ./server_configs/scripts/add_mysql.sh
  #     - sudo ./server_configs/scripts/add_mysql.sh
  #     - sudo apt-get install -y mysql-server
  #     - service mysql start
  #     - mysql -hlocalhost -uroot -ppassword -P3306 -e "show databases;"
  build:
    commands:
      - echo "Running required builds"
      - echo "Setting up environments"
      - python3 -m venv env
      - echo "Activating environments"
      - source env/bin/activate
      - echo "Upgrade pip"
      - python3 -m pip install --upgrade pip
      - echo "Check current dir"
      - pwd
      - echo "Check what is in the dir"
      - ls -lart
      - echo "Install python requirements"
      - pip install -r requirements.txt
      - mv backend/appspec.yml .
      - ls -lart 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - 'backend/**/*'
    # - 'requirements.txt'
    - 'appspec.yml'
cache:
  paths:
    - '/root/.cache/pip/**/*'
    - '/var/cache/apt/archives/**/*'
    - '/var/lib/apt/lists/**/*'
    - '/etc/apt/sources.list.d/mysql.list'
    - '/etc/apt/sources.list'