version: 0.0
os: linux
files:
  - source: js_client
    destination: /opt/var/frontend
#   - source: server_configs/nginx/backend.conf
#     destination: /etc/nginx/sites-enabled/
#     runas: ubuntu
#   - source: server_configs/nginx/backend.conf
#     destination: /etc/nginx/sites-available/
#     runas: ubuntu
#   - source: server_configs/supervisor/backend_supervisor.conf
#     destination: /etc/supervisor/conf.d
#     runas: ubuntu
hooks:
  # BeforeInstall:
  #     - location: server_configs/scripts/before_install.sh
  AfterInstall:
      - location: /opt/var/frontend/after_install.sh